import { customerModel } from "./customer.model";

export const customers:customerModel[]=[{
        id:'c1',
        sex: 'female',
        firstName: 'Michele',
        lastName: 'Avery',
        address: '346 Cedar Ave',
        city: 'Dallas',
        state: 'Texas',
        orderTotal: 169989,
    },
    {
        id:'c2',
        sex: 'male',
        firstName: 'Ward',
        lastName: 'Bell',
        address: '12 Ocean View St.',
        city: 'Dallas',
        state: 'Texas',
        orderTotal: 124994,
    },
    {
        id:'c3',
        sex: 'female',
        firstName: 'Laura',
        lastName: 'Patterson',
        address: '89 Pine Street',
        city: 'Austin',
        state: 'Texas',
        orderTotal: 45999,
    },
    {
        id:'c4',
        sex: 'male',
        firstName: 'Jonathan',
        lastName: 'Reeves',
        address: '501 Sunset Blvd',
        city: 'Houston',
        state: 'Texas',
        orderTotal: 239500,
    },
    {
        id:'c5',
        sex: 'female',
        firstName: 'Emily',
        lastName: 'Clark',
        address: '77 Maple Lane',
        city: 'San Antonio',
        state: 'Texas',
        orderTotal: 98550,
    },
    {
        id:'c6',
        sex: 'male',
        firstName: 'Chris',
        lastName: 'Henderson',
        address: '220 Forest Hill Rd',
        city: 'Fort Worth',
        state: 'Texas',
        orderTotal: 174300,
    },
    {
        id:'c7',
        sex: 'female',
        firstName: 'Nicole',
        lastName: 'Santos',
        address: '14 Riverside Dr.',
        city: 'El Paso',
        state: 'Texas',
        orderTotal: 60500,
    },
    {
        id:'c8',
        sex: 'male',
        firstName: 'Daniel',
        lastName: 'Morales',
        address: '45 Hillcrest Rd',
        city: 'Arlington',
        state: 'Texas',
        orderTotal: 112300,
    },
    {
        id:'c9',
        sex: 'female',
        firstName: 'Samantha',
        lastName: 'Lopez',
        address: '98 Willow Creek',
        city: 'Plano',
        state: 'Texas',
        orderTotal: 78500,
    },
    {
        id:'c10',
        sex: 'male',
        firstName: 'Brandon',
        lastName: 'Turner',
        address: '301 Ridgewood St',
        city: 'Lubbock',
        state: 'Texas',
        orderTotal: 154000,
    },
    {
        id:'c11',
        sex: 'female',
        firstName: 'Hannah',
        lastName: 'Stevens',
        address: '18 Birchwood Ave',
        city: 'Corpus Christi',
        state: 'Texas',
        orderTotal: 33450,
    },
    {
        id:'c12',
        sex: 'male',
        firstName: 'Ethan',
        lastName: 'Baker',
        address: '772 Oak Street',
        city: 'Garland',
        state: 'Texas',
        orderTotal: 91000,
    },
    {
        id:'c13',
        sex: 'female',
        firstName: 'Alyssa',
        lastName: 'Carpenter',
        address: '390 Liberty Hill',
        city: 'Irving',
        state: 'Texas',
        orderTotal: 129500,
    },
    {
        id:'c14',
        sex: 'male',
        firstName: 'Marcus',
        lastName: 'Grant',
        address: '6 Green Valley Rd',
        city: 'Laredo',
        state: 'Texas',
        orderTotal: 47800,
    },
    {
        id:'c15',
        sex: 'female',
        firstName: 'Julia',
        lastName: 'Keller',
        address: '510 Meadow Lane',
        city: 'Amarillo',
        state: 'Texas',
        orderTotal: 205000,
    },
    {
        id:'c16',
        sex: 'male',
        firstName: 'Owen',
        lastName: 'Perry',
        address: '66 Highland Dr',
        city: 'Waco',
        state: 'Texas',
        orderTotal: 67900,
    },
    {
        id:'c17',
        sex: 'female',
        firstName: 'Rachel',
        lastName: 'Dawson',
        address: '820 Creekside Pl',
        city: 'Midland',
        state: 'Texas',
        orderTotal: 144200,
    },
    {
        id:'c18',
        sex: 'male',
        firstName: 'Alex',
        lastName: 'Ferguson',
        address: '32 Brookside Blvd',
        city: 'Frisco',
        state: 'Texas',
        orderTotal: 76500,
    },
    {
        id:'c19',
        sex: 'female',
        firstName: 'Victoria',
        lastName: 'Reyes',
        address: '101 Palm View Dr',
        city: 'Brownsville',
        state: 'Texas',
        orderTotal: 224500,
    },
    {
        id:'c20',
        sex: 'male',
        firstName: 'Liam',
        lastName: 'Sanders',
        address: '12 Heritage Rd',
        city: 'Odessa',
        state: 'Texas',
        orderTotal: 55400,
    },
    {
        id:'c21',
        sex: 'female',
        firstName: 'Chloe',
        lastName: 'Mitchell',
        address: '9 Canyon Ridge',
        city: 'Beaumont',
        state: 'Texas',
        orderTotal: 97000,
    },
    {
        id:'c22',
        sex: 'male',
        firstName: 'Nathan',
        lastName: 'Harris',
        address: '245 Kingsway',
        city: 'Killeen',
        state: 'Texas',
        orderTotal: 188600,
    },
    {
        id:'c23',
        sex: 'female',
        firstName: 'Grace',
        lastName: 'Powell',
        address: '11 Whispering Pines',
        city: 'Round Rock',
        state: 'Texas',
        orderTotal: 81500,
    },
    {
        id:'c24',
        sex: 'male',
        firstName: 'Isaac',
        lastName: 'Coleman',
        address: '700 Timber Rd',
        city: 'Tyler',
        state: 'Texas',
        orderTotal: 143900,
    },
    {
        id:'c25',
        sex: 'female',
        firstName: 'Lily',
        lastName: 'Jennings',
        address: '554 Creek Bend',
        city: 'Wichita Falls',
        state: 'Texas',
        orderTotal: 33200,
    },
    {
        id:'c26',
        sex: 'male',
        firstName: 'Adam',
        lastName: 'Wells',
        address: '87 Cottonwood St',
        city: 'College Station',
        state: 'Texas',
        orderTotal: 199000,
    },
    {
        id:'c27',
        sex: 'female',
        firstName: 'Natalie',
        lastName: 'Hughes',
        address: '221 Evergreen Ln',
        city: 'Lewisville',
        state: 'Texas',
        orderTotal: 122500,
    },
    {
        id:'c28',
        sex: 'male',
        firstName: 'Jason',
        lastName: 'Ward',
        address: '990 Hilltop Dr',
        city: 'Abilene',
        state: 'Texas',
        orderTotal: 60500,
    },
    {
        id:'c29',
        sex: 'female',
        firstName: 'Hailey',
        lastName: 'Bryant',
        address: '19 Spring Valley',
        city: 'San Angelo',
        state: 'Texas',
        orderTotal: 148700,
    },
    {
        id:'c30',
        sex: 'male',
        firstName: 'Connor',
        lastName: 'Reed',
        address: '501 Ridgecrest',
        city: 'Pearland',
        state: 'Texas',
        orderTotal: 47300,
    },
    {
        id:'c31',
        sex: 'female',
        firstName: 'Ella',
        lastName: 'Gibson',
        address: '600 Westwood Dr',
        city: 'Allen',
        state: 'Texas',
        orderTotal: 137800,
    },
    {
        id:'c32',
        sex: 'male',
        firstName: 'Logan',
        lastName: 'Ford',
        address: '77 Mountain Pass',
        city: 'League City',
        state: 'Texas',
        orderTotal: 95500,
    },
    {
        id:'c33',
        sex: 'female',
        firstName: 'Charlotte',
        lastName: 'Harvey',
        address: '28 Willow Ridge',
        city: 'Sugar Land',
        state: 'Texas',
        orderTotal: 215900,
    },
    {
        id:'c34',
        sex: 'male',
        firstName: 'Mason',
        lastName: 'Fowler',
        address: '83 Grand Oak Dr',
        city: 'The Woodlands',
        state: 'Texas',
        orderTotal: 189400,
    },
    {
        id:'c35',
        sex: 'female',
        firstName: 'Zoe',
        lastName: 'Hart',
        address: '450 Pinecrest',
        city: 'Richardson',
        state: 'Texas',
        orderTotal: 68000,
    },
    {
        id:'c36',
        sex: 'male',
        firstName: 'Caleb',
        lastName: 'Hunter',
        address: '72 Creek View',
        city: 'Carrollton',
        state: 'Texas',
        orderTotal: 158700,
    },
    {
        id:'c37',
        sex: 'female',
        firstName: 'Madison',
        lastName: 'Cross',
        address: '120 Maple View',
        city: 'Pasadena',
        state: 'Texas',
        orderTotal: 277500,
    },
    {
        id:'c38',
        sex: 'male',
        firstName: 'Henry',
        lastName: 'Wade',
        address: '5 Golden Leaf',
        city: 'McKinney',
        state: 'Texas',
        orderTotal: 33900,
    },
    {
        id:'c39',
        sex: 'female',
        firstName: 'Ariana',
        lastName: 'Steele',
        address: '909 Meadow Woods',
        city: 'Mesquite',
        state: 'Texas',
        orderTotal: 128500,
    },
    {
        id:'c40',
        sex: 'male',
        firstName: 'Patrick',
        lastName: 'Knight',
        address: '310 Lone Star Ln',
        city: 'McAllen',
        state: 'Texas',
        orderTotal: 99000,
    },
    {
        id:'c41',
        sex: 'female',
        firstName: 'Bella',
        lastName: 'Grant',
        address: '55 Oak Ridge',
        city: 'Baytown',
        state: 'Texas',
        orderTotal: 203400,
    },
    {
        id:'c42',
        sex: 'male',
        firstName: 'Gavin',
        lastName: 'Moss',
        address: '8 Cedar Hollow',
        city: 'Cedar Park',
        state: 'Texas',
        orderTotal: 77600,
    },
    {
        id:'c43',
        sex: 'female',
        firstName: 'Scarlett',
        lastName: 'Barlow',
        address: '700 Sunrise Dr',
        city: 'Georgetown',
        state: 'Texas',
        orderTotal: 164000,
    },
    {
        id:'c44',
        sex: 'male',
        firstName: 'Julian',
        lastName: 'McCarthy',
        address: '23 Elm Hill',
        city: 'Haltom City',
        state: 'Texas',
        orderTotal: 84000,
    },
    {
        id:'c45',
        sex: 'female',
        firstName: 'Maya',
        lastName: 'Goodman',
        address: '801 River Valley',
        city: 'Temple',
        state: 'Texas',
        orderTotal: 255000,
    },
    {
        id:'c46',
        sex: 'male',
        firstName: 'Sean',
        lastName: 'Douglas',
        address: '17 Timber Hollow',
        city: 'Euless',
        state: 'Texas',
        orderTotal: 155700,
    },
    {
        id:'c47',
        sex: 'female',
        firstName: 'Harper',
        lastName: 'Lang',
        address: '33 Park Meadow',
        city: 'Flower Mound',
        state: 'Texas',
        orderTotal: 77550,
    },
    {
        id:'c48',
        sex: 'male',
        firstName: 'Dylan',
        lastName: 'Vargas',
        address: '66 Creek View Dr',
        city: 'Longview',
        state: 'Texas',
        orderTotal: 133200,
    },
    {
        id:'c49',
        sex: 'female',
        firstName: 'Evelyn',
        lastName: 'Summers',
        address: '901 Shadow Creek',
        city: 'Conroe',
        state: 'Texas',
        orderTotal: 122800,
    },
    {
        id:'c50',
        sex: 'male',
        firstName: 'Adrian',
        lastName: 'Palmer',
        address: '14 Oak Creek Dr',
        city: 'Bryan',
        state: 'Texas',
        orderTotal: 187900,
    }
];