import { customerModel } from "./customer.model";

export const customers:customerModel[]=[{
        id:'c1',
        sex: 'female',
        firstName: 'Michele',
        lastName: 'Avery',
        address: '346 Cedar Ave',
        city: 'Dallas',
        state: 'Texas',
        orderTotal: 169989,
    },
    {
        id:'c2',
        sex: 'male',
        firstName: 'Ward',
        lastName: 'Bell',
        address: '12 Ocean View St.',
        city: 'Dallas',
        state: 'Texas',
        orderTotal: 124994, 
    },
    {
        id:'c3',
        sex: 'female',
        firstName: 'Laura',
        lastName: 'Patterson',
        address: '89 Pine Street',
        city: 'Austin',
        state: 'Texas',
        orderTotal: 45999,
    },
    {
        id:'c4',
        sex: 'male',
        firstName: 'Jonathan',
        lastName: 'Reeves',
        address: '501 Sunset Blvd',
        city: 'Houston',
        state: 'Texas',
        orderTotal: 239500,
    },
    {
        id:'c5',
        sex: 'female',
        firstName: 'Emily',
        lastName: 'Clark',
        address: '77 Maple Lane',
        city: 'San Antonio',
        state: 'Texas',
        orderTotal: 98550,
    },
    {
        id:'c6',
        sex: 'male',
        firstName: 'Chris',
        lastName: 'Henderson',
        address: '220 Forest Hill Rd',
        city: 'Fort Worth',
        state: 'Texas',
        orderTotal: 174300,
    },
    {
        id:'c7',
        sex: 'female',
        firstName: 'Nicole',
        lastName: 'Santos',
        address: '14 Riverside Dr.',
        city: 'El Paso',
        state: 'Texas',
        orderTotal: 60500,
    }
]